spring:
  application:
    name: course-app  # The name of your application

  config:
    import: "configserver:http://localhost:8888"  # URL of the Config Server

  cloud:
    config:
      fail-fast: true
      profile: development  # Default profile to use (you can also configure this via environment variables)
      label: main  # Git branch to use for configurations (if using a Git-based Config Server)

  server:
    port: 8080  # The port your application will run on

  logging:
    level:
      root: INFO  # Set the logging level for the application

# Optional: additional configuration settings
management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all actuator endpoints (for debugging and monitoring)
  endpoint:
    health:
      show-details: always  # Show detailed health info
